name: Publish Design System

on:
  push:
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Publish to GitHub Packages
        run: ./gradlew :designsystem:publish
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create Swift Package
        run: |
          echo '
          // swift-tools-version:5.3
          import PackageDescription

          let package = Package(
              name: "DesignSystem",
              platforms: [
                  .iOS(.v13)
              ],
              products: [
                  .library(
                      name: "DesignSystem",
                      targets: ["DesignSystem"]
                  ),
              ],
              dependencies: [],
              targets: [
                  .binaryTarget(
                      name: "DesignSystem",
                      path: "./DesignSystem.xcframework"
                  )
              ]
          )
          ' > Package.swift
          git config --global user.email "action@github.com"
          git config --global user.name "GitHub Action"
          git add Package.swift
          git commit -m "Create Package.swift"
          git push