build:
  maxIssues: 0
  excludeCorrectable: false
  weights:
  excludes:
    - '**/build/**'
    - '**/generated/**'
    - '**/composeApp/build/**'
    - '**/composeApp/generated/**'
    - '**/composeApp/**/*.kt'
    - '**/preview/**'
    - '**/ui/theme/Colors.kt'

config:
  validation: true
  warningsAsErrors: false
  checkExhaustiveness: false
  excludes: ''

processors:
  active: true
  exclude:
    - 'DetektProgressListener'

console-reports:
  active: true
  exclude:
    - 'ProjectStatisticsReport'
    - 'ComplexityReport'
    - 'NotificationReport'
    - 'FindingsReport'
    - 'FileBasedFindingsReport'

output-reports:
  active: true

comments:
  active: true

complexity:
  active: true
  CognitiveComplexMethod:
    active: false
  ComplexCondition:
    active: true
    threshold: 4
  CyclomaticComplexMethod:
    active: true
    threshold: 15
    ignoreSingleWhenExpression: false
    ignoreSimpleWhenEntries: false
    ignoreNestingFunctions: false
    nestingFunctions:
      - 'also'
      - 'apply'
      - 'forEach'
      - 'isNotNull'
      - 'ifNull'
      - 'let'
      - 'run'
      - 'use'
      - 'with'
  LargeClass:
    active: true
    threshold: 600
  LongMethod:
    active: true
    threshold: 60
    ignoreAnnotated:
      - 'Composable'
      - 'Preview'
  LongParameterList:
    active: true
    functionThreshold: 6
    constructorThreshold: 7
    ignoreDefaultParameters: false
    ignoreDataClasses: true
    ignoreAnnotated:
      - 'Composable'
      - 'Preview'
  NestedBlockDepth:
    active: true
    threshold: 4
    ignoreAnnotated:
      - 'Composable'
  TooManyFunctions:
    active: true
    thresholdInFiles: 11
    thresholdInClasses: 11
    ignoreAnnotatedFunctions:
      - 'Composable'

coroutines:
  active: true
  GlobalCoroutineUsage:
    active: false
  InjectDispatcher:
    active: true
    dispatcherNames:
      - 'IO'
      - 'Default'
      - 'Unconfined'
  RedundantSuspendModifier:
    active: true
  SleepInsteadOfDelay:
    active: true
  SuspendFunSwallowedCancellation:
    active: false
  SuspendFunWithCoroutineScopeReceiver:
    active: false
  SuspendFunWithFlowReturnType:
    active: true

empty-blocks:
  active: true

exceptions:
  active: true
  InstanceOfCheckForException:
    active: true
  PrintStackTrace:
    active: true
  RethrowCaughtException:
    active: true
  ReturnFromFinally:
    active: true
    ignoreLabeled: false
  SwallowedException:
    active: true
  ThrowingExceptionFromFinally:
    active: true
  ThrowingExceptionsWithoutMessageOrCause:
    active: true
  ThrowingNewInstanceOfSameException:
    active: true
  TooGenericExceptionCaught:
    active: true
    exceptionNames:
      - 'ArrayIndexOutOfBoundsException'
      - 'Error'
      - 'Exception'
      - 'IllegalMonitorStateException'
      - 'IndexOutOfBoundsException'
      - 'NullPointerException'
      - 'RuntimeException'
      - 'Throwable'
  TooGenericExceptionThrown:
    active: true

naming:
  active: true
  FunctionNaming:
    active: true
    ignoreAnnotated:
      - 'Composable'
      - 'Preview'
  FunctionParameterNaming:
    active: true
  VariableNaming:
    active: true
  TopLevelPropertyNaming:
    active: true
  ClassNaming:
    active: true
  ObjectPropertyNaming:
    active: true
  PackageNaming:
    active: true
  MatchingDeclarationName:
    active: false

performance:
  active: true
  ForEachOnRange:
    active: true
    excludes:
      - '**/*Composable*.*'
  SpreadOperator:
    active: true
    excludes:
      - '**/*Composable*.*'
  UnnecessaryTemporaryInstantiation:
    active: true

potential-bugs:
  active: true
  AvoidReferentialEquality:
    active: true
  DoubleMutabilityForCollection:
    active: true
  EqualsAlwaysReturnsTrueOrFalse:
    active: true
  EqualsWithHashCodeExist:
    active: true
  HasPlatformType:
    active: true
  MapGetWithNotNullAssertionOperator:
    active: true
  UnnecessaryNotNullOperator:
    active: true
  UnnecessarySafeCall:
    active: true
  UnsafeCallOnNullableType:
    active: true
  UnsafeCast:
    active: true
  UnusedUnaryOperator:
    active: true
  UselessPostfixExpression:
    active: true

style:
  active: true
  MagicNumber:
    active: true
    excludes:
      - '**/ui/theme/Colors.kt'
      - '**/generated/**'
      - '**/*Composable*.*'
  FunctionOnlyReturningConstant:
    active: true
  ReturnCount:
    active: true
    max: 2
    ignoreAnnotated:
      - 'Composable'
  VarCouldBeVal:
    active: true
  UnnecessaryLet:
    active: false
