name: Build and Test

on:
  workflow_run:
    workflows: ["Lint"]
    types:
      - completed

jobs:
  build_and_test:
    name: Build and Test
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Run tests
        run: ./gradlew check

      - name: Build
        run: ./gradlew assemble
