name: Develop

on:
  push:
    branches-ignore:
      - 'main'

jobs:
  build_and_publish:
    name: Build and Publish Snapshot
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Necessário para o git describe

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Run Detekt
        run: ./gradlew detekt

      - name: Build
        run: ./gradlew assembleDebug

      - name: Run tests
        run: ./gradlew testDebugUnitTest

      - name: Determine Version
        id: version
        run: echo "VERSION_NAME=$(git describe --tags --always)-SNAPSHOT" >> $GITHUB_ENV

      - name: Publish KMP Library to GitHub Packages
        run: ./gradlew :designsystem:publish -PVERSION_NAME=${{ env.VERSION_NAME }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
