name: KMMBridge-Release
on:
  push:
    branches-ignore:
      - 'main'

jobs:
  call-publish:
    uses: ./.github/workflows/base.yml
    with:
      build-debug: false
    permissions:
      contents: write   # permite criar Releases
      packages: write   # permite enviar pacotes